train:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 100
    split: [0, 94]
    seed: 0
    num_steps: 100
    batch_size: ${batch_size}
val:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 100
    split: [95, 99]
    seed: 1
    num_steps: 10
    batch_size: ${batch_size}