train:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 200000
    split: [0, 2000]
    seed: 0
    num_steps: 1000
    batch_size: ${batch_size}
val:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 200000
    split: [189999, 200000]
    seed: 1
    num_steps: 100
    batch_size: ${batch_size}
