train:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 250000
    split: [0, 237500]
    seed: 0
    num_steps: 1000
    batch_size: ${batch_size}
val:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 250000
    split: [237500, 249999]
    seed: 1
    num_steps: 100
    batch_size: ${batch_size}