train:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 300000
    split: [0, 284997]
    seed: 0
    num_steps: 1000
    batch_size: ${batch_size}
val:
  target: ${data.target}
  params:
    DATA_ROOT: ${paths.sbi_benchmark}
    num_samples: 300000
    split: [284998, 299999]
    seed: 1
    num_steps: 100
    batch_size: ${batch_size}
